on:
  pull_request:
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
  
      - name: Build and Test
        run: mvn verify
